embedding_size: 64
feat_embed_dim: 64

n_layers: 2
mm_image_weight: [0.1]
aggr_mode: ['add']
knn_k: [10]
k: [30, 40, 50]
n_mm_layers: [2]
u_layers: [1, 2]
learning_rate: [1e-4]
reg_weight: [0.001]
hyper_parameters: ["mm_image_weight", "k", "u_layers", "n_mm_layers", "knn_k", "aggr_mode", "reg_weight", "learning_rate"]